[versions]
# Core Build Tools
agp = "8.13.2"
kotlin = "2.3.0"
ksp = "2.3.7" # Strictly matched to Kotlin version

# AndroidX Lifecycle & UI
coreKtx = "1.18.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
composeBom = "2026.03.00"
navigationCompose = "2.9.7"
coreSplashscreen = "1.2.0"

# Dependency Injection
hilt = "2.58" # Latest stable to fix KSP processing errors
hiltNavigationCompose = "1.3.0" # Updated to match Nav 2.9.x
kotlinMetadataJvm = "2.2.0"    # Fallback workaround if Hilt throws a metadata version exception


# Data & Networking
retrofit = "2.11.0"
okhttp = "4.12.0"
kotlinxSerialization = "1.7.0"
kotlinxDatetime = "0.8.0"
datastore = "1.2.1"

# Image Loading & SDKs
coil = "3.0.0" # Coil 3.0 is optimized for Kotlin 2.0+ & KMP
ciqCompanionAppSdk = "2.2.0"
capsuleVersion = "2.1.1"

# Testing / UI Support
uiUnit = "1.10.6"
countryPicker = "3.0.1"
backdrop = "1.0.6"
imageCropper = "2.2.8"
vico = "3.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit", version.ref = "uiUnit" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# Networking (For :core-network)
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# DataStore (For :core-network)
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# UI & Navigation (For :core-ui & :app)
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
kotlin-metadata-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-metadata-jvm", version.ref = "kotlinMetadataJvm" }

# Spalsh screen
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

# Garmin Connect
ciq-companion-app-sdk = { group = "com.garmin.connectiq", name = "ciq-companion-app-sdk", version.ref = "ciqCompanionAppSdk" }

# Kotlinx DateTime
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

# Capsule
capsule = { group = "io.github.kyant0", name = "capsule", version.ref = "capsuleVersion" }

# Country code picker
country-picker = { group = "com.github.arpitkatiyar1999", name = "Country-Picker", version.ref = "countryPicker" }

# Glass UI
backdrop = { group = "io.github.kyant0", name = "backdrop", version.ref = "backdrop" }

# Image Croper
ucrop = { group = "com.github.yalantis", name = "ucrop", version.ref = "imageCropper" }

# The core Vico Compose library
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }

# The Material 3 theming extension for Vico
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }